/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2023-03-29 21:02:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import uk.ac.ucl.items.Item;
import uk.ac.ucl.items.ItemList;
import uk.ac.ucl.htmlfilter.Filter;

public final class noteContents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("uk.ac.ucl.notes.Item");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("uk.ac.ucl.notes.ItemList");
    _jspx_imports_classes.add("uk.ac.ucl.htmlfilter.Filter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
ItemList currList = (ItemList) request.getAttribute("list");
      out.write('\r');
      out.write('\n');
session.setAttribute("curr", currList); //  Stores current list as an attribute (needed for deletion, adding, going back)
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>");
      out.print(currList.getContents());
      out.write("</title>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>");
      out.print(currList.getContents());
      out.write("</h1>\r\n");
      out.write("<form method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goback.html\">\r\n");
      out.write("  <input class=\"noteButton\" type=\"submit\" name=\"content\" value=\"Go back\">\r\n");
      out.write("</form>\r\n");
      out.write("<table>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <h2>Item</h2>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <h2>Delete Item</h2>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <h2>Edit Item</h2>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  ");

  List<Item> items = currList.getItems();
  List<ItemList> lists = currList.getLists();
  int listIndex = 0, itemIndex = 0;
  while(listIndex < lists.size() && itemIndex < items.size()) {
    Item item = items.get(itemIndex);
    ItemList list = lists.get(listIndex);
    if (item.getId() < list.getId()) {
      session.setAttribute(item.getContents(), item);
      String content = Filter.parse(item.getContents());
  
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("          <p>");
      out.print(item.display());
      out.write("</p>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("          <form method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deleteitem.html\">\r\n");
      out.write("            <button class=\"deleteButton\"  onsubmit=\"return confirm('Do you really want to delete this item?');\" type=\"submit\" name=\"item\" value=\"");
      out.print(content);
      out.write("\">Delete</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("          <form method=\"POST\" onsubmit=\"return submitForm(this)\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/edititem.html\">\r\n");
      out.write("            <input type=\"text\" class = \"inputText\" name=\"userinput\" value=\"");
      out.print(content);
      out.write("\" placeholder=\"");
      out.print(item.getEditText());
      out.write("\"/>\r\n");
      out.write("            <button class=\"renameButton\" type=\"submit\" name=\"item\" value=\"");
      out.print(content);
      out.write("\">Save Changes</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    ");
itemIndex++;
    }else{
      session.setAttribute(list.getContents(), list);
      String content = Filter.parse(list.getContents());
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("          <form method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getlistcontent.html\">\r\n");
      out.write("            <input class=\"noteButton\" type=\"submit\" name=\"content\" value=\"");
      out.print(content);
      out.write("\">\r\n");
      out.write("          </form>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("          <form method=\"POST\" onsubmit=\"return confirm('Do you really want to delete this item?');\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deletelist.html\">\r\n");
      out.write("            <button class=\"deleteButton\" type=\"submit\" name=\"list\" value=\"");
      out.print(content);
      out.write("\">Delete</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("          <form method=\"POST\" onsubmit=\"return submitForm(this)\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/renamelist.html\">\r\n");
      out.write("            <input type=\"text\" class = \"inputText\" name=\"userinput\" value=\"");
      out.print(content);
      out.write("\" placeholder=\"");
      out.print(list.getEditText());
      out.write("\"/>\r\n");
      out.write("            <button class=\"renameButton\" type=\"submit\" name=\"list\" value=\"");
      out.print(content);
      out.write("\">Rename</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    ");
listIndex++;
    }
      out.write('\r');
      out.write('\n');
}
      out.write("\r\n");
      out.write("  ");

  while (itemIndex < items.size()){
    Item item = items.get(itemIndex);
    session.setAttribute(item.getContents(), item);
    String content = Filter.parse(item.getContents());

      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>\r\n");
      out.write("        <p>");
      out.print(item.display());
      out.write("</p>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td>\r\n");
      out.write("        <form method=\"POST\" onsubmit=\"return confirm('Do you really want to delete this item?');\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deleteitem.html\">\r\n");
      out.write("          <button class=\"deleteButton\"  type=\"submit\" name=\"item\" value=\"");
      out.print(content);
      out.write("\">Delete</button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td>\r\n");
      out.write("        <form method=\"POST\" onsubmit=\"return submitForm(this)\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/edititem.html\">\r\n");
      out.write("          <input type=\"text\" class = \"inputText\" name=\"userinput\" value=\"");
      out.print(content);
      out.write("\" placeholder=\"");
      out.print(item.getEditText());
      out.write("\"/>\r\n");
      out.write("          <button class=\"renameButton\" type=\"submit\" name=\"item\" value=\"");
      out.print(content);
      out.write("\">Save Changes</button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
itemIndex++;
  }
    while (listIndex < lists.size()){
      Item list = lists.get(listIndex);
      session.setAttribute(list.getContents(), list);
      String content = Filter.parse(list.getContents());
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("          <form method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getlistcontent.html\">\r\n");
      out.write("            <input class=\"noteButton\" type=\"submit\" name=\"content\" value=\"");
      out.print(content);
      out.write("\">\r\n");
      out.write("          </form>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("          <form method=\"POST\" onsubmit=\"return confirm('Do you really want to delete this item?');\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deletelist.html\">\r\n");
      out.write("            <button class=\"deleteButton\" type=\"submit\" name=\"list\" value=\"");
      out.print(content);
      out.write("\">Delete</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("          <form method=\"POST\" onsubmit=\"return submitForm(this)\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/renamelist.html\">\r\n");
      out.write("            <input type=\"text\" class = \"inputText\" name=\"userinput\" value=\"");
      out.print(content);
      out.write("\" placeholder=\"");
      out.print(list.getEditText());
      out.write("\"/>\r\n");
      out.write("            <button class=\"renameButton\" type=\"submit\" name=\"list\" value=\"");
      out.print(content);
      out.write("\">Rename</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
listIndex++;
}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<form class=\"inputForm\" onsubmit=\"return submitForm(this)\" method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/additem.html\"> <!-- this indicates a request which gets mapped to a servlet\r\n");
      out.write("     could have multiple requests to same servlet -->\r\n");
      out.write("  <input type=\"text\" class=\"inputText\" name=\"userinput\" placeholder=\"Enter contents here\"/>\r\n");
      out.write("  <input type=\"submit\" class=\"searchButton\" name=\"add\" value=\"Add text\"/>\r\n");
      out.write("  <input type=\"submit\" class=\"searchButton\" name=\"add\" value=\"Add note\"/>\r\n");
      out.write("  <input type=\"submit\" class=\"searchButton\" name=\"add\" value=\"Add url\"/>\r\n");
      out.write("  <input type=\"submit\" class=\"searchButton\" name=\"add\" value=\"Add image\"/>\r\n");
      out.write("</form>\r\n");
      out.write("<script src=\"validation.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
